/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Autenticacao_Controller;
import Model.Codigo_Atos_Model;
import Model.Selos_Model;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class Impressao_Autenticacao_View extends javax.swing.JDialog {

    private String sql_busca;
    private int id_autenticacao;

    /**
     * Creates new form Impressao_Autenticacao_View
     */
    public Impressao_Autenticacao_View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void preencher_tabela_autenticaoes(List<Selos_Model> dados) {

        DefaultTableModel tabela = (DefaultTableModel) tbl_autenticacoes.getModel();
        tabela.setNumRows(0);

        for (Selos_Model dado : dados) {

            tabela.addRow(new Object[]{
                dado.getId_selo(),
                dado.getseqLetras() + dado.getseqNumeros(),
                dado.getData_ato(),
                dado.getSituacao_impresso()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        check_todas_autenticacao = new javax.swing.JCheckBox();
        check_auten_nao_impressa = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        campo_data_inicio = new javax.swing.JFormattedTextField();
        campo_data_fim = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_autenticacoes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_imprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio de Autenticações");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opções"));

        check_todas_autenticacao.setText("Todas autenticações");
        check_todas_autenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_todas_autenticacaoActionPerformed(evt);
            }
        });

        check_auten_nao_impressa.setText("Não impressas");
        check_auten_nao_impressa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_auten_nao_impressaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_todas_autenticacao)
                    .addComponent(check_auten_nao_impressa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check_todas_autenticacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_auten_nao_impressa)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Periodo"));

        try {
            campo_data_inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_data_inicio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                campo_data_inicioCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        try {
            campo_data_fim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Data inicio:");

        jLabel2.setText("Data Fim:");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(campo_data_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(campo_data_fim))
                    .addComponent(btn_buscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_data_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_data_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbl_autenticacoes.setBackground(new java.awt.Color(117, 214, 233));
        tbl_autenticacoes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbl_autenticacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ident. selo", "Selo utilizado", "Data", "Impresso?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_autenticacoes.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_autenticacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_autenticacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_autenticacoes);
        if (tbl_autenticacoes.getColumnModel().getColumnCount() > 0) {
            tbl_autenticacoes.getColumnModel().getColumn(0).setMinWidth(100);
            tbl_autenticacoes.getColumnModel().getColumn(0).setMaxWidth(120);
            tbl_autenticacoes.getColumnModel().getColumn(2).setResizable(false);
            tbl_autenticacoes.getColumnModel().getColumn(3).setMinWidth(40);
            tbl_autenticacoes.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("AUTENTICAÇÕES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/impressora.png"))); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.setFocusable(false);
        btn_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_imprimir);
        jToolBar1.add(jSeparator1);

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/stop_pequeno.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_sair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed

        Imprimir_Relatorio imprimir = new Imprimir_Relatorio(null, false, id_autenticacao, Codigo_Atos_Model.CODIGO_AUTENTICACAO);
        imprimir.setVisible(true);
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void check_todas_autenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_todas_autenticacaoActionPerformed

        // se a busca for por todas as autenticações lançadas, incluindo as não impressas
        // passamos esta sql para o controller
        if (check_todas_autenticacao.isSelected()) {

            check_auten_nao_impressa.setSelected(false);
            sql_busca = "select cadastro.tblselos.id, cadastro.tblselos.data_ato, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.custo, cadastro.tblselos.impresso from cadastro.tblselos inner join cadastro.tblautenticacao on cadastro.tblautenticacao.id_selo = cadastro.tblselos.id where cadastro.tblselos.impresso ='S' OR cadastro.tblselos.impresso ='N' ";

            Autenticacao_Controller control = new Autenticacao_Controller();
            List<Selos_Model> autenticacoes = control.buscar_autenticacao(sql_busca);
            preencher_tabela_autenticaoes(autenticacoes);

        }

    }//GEN-LAST:event_check_todas_autenticacaoActionPerformed

    private void campo_data_inicioCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campo_data_inicioCaretPositionChanged
        // TODO add your handling code her;
    }//GEN-LAST:event_campo_data_inicioCaretPositionChanged

    private void check_auten_nao_impressaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_auten_nao_impressaActionPerformed
        if (check_auten_nao_impressa.isSelected()) {
            check_todas_autenticacao.setSelected(false);

            sql_busca = "select cadastro.tblselos.id, cadastro.tblselos.data_ato, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.custo, cadastro.tblselos.impresso from cadastro.tblselos inner join cadastro.tblautenticacao on cadastro.tblautenticacao.id_selo = cadastro.tblselos.id where cadastro.tblselos.impresso ='N' ";

            Autenticacao_Controller control = new Autenticacao_Controller();
            List<Selos_Model> autenticacoes = control.buscar_autenticacao(sql_busca);
            preencher_tabela_autenticaoes(autenticacoes);
        }
    }//GEN-LAST:event_check_auten_nao_impressaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        if (campo_data_fim.getText().isEmpty() || campo_data_inicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha os campos de data inicio e data fim", "Mensagem", JOptionPane.ERROR_MESSAGE);
        } else {

            String data_inicio = campo_data_inicio.getText();
            String data_fim = campo_data_fim.getText();

            DateTimeFormatter form = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate d1 = LocalDate.parse(data_inicio, form);
            LocalDate d2 = LocalDate.parse(data_fim, form);

            sql_busca = "select cadastro.tblselos.data_ato, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.custo, cadastro.tblselos.impresso, cadastro.tblselos.id from cadastro.tblselos inner join cadastro.tblautenticacao on cadastro.tblautenticacao.id_selo = cadastro.tblselos.id where cadastro.tblselos.data_ato >=' " + d1 + " ' " + " and cadastro.tblselos.data_ato <=' " + d2 + " ' ";

            Autenticacao_Controller control = new Autenticacao_Controller();
            List<Selos_Model> autenticacoes = control.buscar_autenticacao(sql_busca);
            preencher_tabela_autenticaoes(autenticacoes);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tbl_autenticacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_autenticacoesMouseClicked

        int linha = tbl_autenticacoes.getSelectedRow();
        id_autenticacao = Integer.parseInt(tbl_autenticacoes.getValueAt(linha, 0).toString());

//        System.out.println(id_autenticacao);
    }//GEN-LAST:event_tbl_autenticacoesMouseClicked

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impressao_Autenticacao_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impressao_Autenticacao_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impressao_Autenticacao_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impressao_Autenticacao_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Impressao_Autenticacao_View dialog = new Impressao_Autenticacao_View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JFormattedTextField campo_data_fim;
    private javax.swing.JFormattedTextField campo_data_inicio;
    private javax.swing.JCheckBox check_auten_nao_impressa;
    private javax.swing.JCheckBox check_todas_autenticacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_autenticacoes;
    // End of variables declaration//GEN-END:variables
}
