/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Reconhecer_Assinatura_Controller;
import Model.Codigo_Atos_Model;
import Model.Pessoas_Model;
import Model.Selos_Model;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class Imprimir_Recon_Assinatura_View extends javax.swing.JDialog {

    private String id_selo;
    private int linha_selecionada = 0;
    private int contador = 0;

    /**
     * Creates new form Imprimir_Recon_Assinatura_View
     */
    public Imprimir_Recon_Assinatura_View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Preenche a tabela com as informações dos selos que foram utilizados em
     * reconhecimento de assinaturas
     *
     * @param dados
     */
    private void preencher_tabela_selos(List<Selos_Model> dados) {

        DefaultTableModel tabela = (DefaultTableModel) tbl_selos.getModel();
        tabela.setNumRows(0);

        for (Selos_Model dado : dados) {

            tabela.addRow(new Object[]{
                dado.getId_selo(),
                dado.getseqLetras() + dado.getseqNumeros(),
                dado.getData_ato(),
                dado.getSituacao_impresso()
            });
        }
    }

    private void preencher_tabela_pessoas(String id_selo) {
        DefaultTableModel tabela = (DefaultTableModel) tbl_pessoas.getModel();
        tabela.setNumRows(0);

        Reconhecer_Assinatura_Controller control = new Reconhecer_Assinatura_Controller();

        List<Pessoas_Model> pessoas = control.buscar_pessoa_recon_firma(id_selo);
        for (Pessoas_Model dado : pessoas) {
            tabela.addRow(new Object[]{
                dado.getId(),
                dado.getNome(),
                dado.getCpf()
            });
        }
    }

    private void preencher_lista_selecionada(String selo_selecionado) {

        // verificando o total de permissao de posições no vetor
        if (contador <= 3) {
            DefaultTableModel tabela = (DefaultTableModel) tbl_selos_selecionados.getModel();
            String sqls = "select cadastro.tblselos.id, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.custo from cadastro.tblselos where cadastro.tblselos.id=" + selo_selecionado;

            Reconhecer_Assinatura_Controller control = new Reconhecer_Assinatura_Controller();
            Selos_Model info_selos = control.preencher_tabela_selos_selecionados(sqls);

            tabela.addRow(new Object[]{
                info_selos.getId_selo(),
                info_selos.getseqLetras() + info_selos.getseqNumeros(),
                info_selos.getCusto()
            });
            contador++;

//            sequencia[contador] = info_selos.getId_selo();
//            System.out.println("Valor vetor[" + contador + "] = " + info_selos.getId_selo());
//            System.out.println("Incrementando contador...");
        } else {
            JOptionPane.showMessageDialog(this, "Quantidade maxima de selos permitidos alcançado", "Mensagem", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoChecks = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        check_todos_reconhecimentos = new javax.swing.JCheckBox();
        check_nao_impressos = new javax.swing.JCheckBox();
        check_opt_periodo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campo_data_inicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        campo_data_fim = new javax.swing.JFormattedTextField();
        btn_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_selos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pessoas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_selos_selecionados = new javax.swing.JTable();
        btn_remover = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btn_imprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar reconhecimento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        check_todos_reconhecimentos.setText("Todos reconhecimentos");
        check_todos_reconhecimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_todos_reconhecimentosActionPerformed(evt);
            }
        });

        check_nao_impressos.setText("Não impressos");
        check_nao_impressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_nao_impressosActionPerformed(evt);
            }
        });

        check_opt_periodo.setText("Escolher periodo");
        check_opt_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_opt_periodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_nao_impressos)
                    .addComponent(check_todos_reconhecimentos)
                    .addComponent(check_opt_periodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(check_todos_reconhecimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_nao_impressos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_opt_periodo)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel2.setText("Data inicial:");

        try {
            campo_data_inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_data_inicial.setEnabled(false);

        jLabel3.setText("Data final:");

        try {
            campo_data_fim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_data_fim.setEnabled(false);

        btn_buscar.setText("Buscar");
        btn_buscar.setEnabled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(campo_data_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(campo_data_fim))
                    .addComponent(btn_buscar))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(campo_data_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo_data_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Reconhecimento de Assinaturas");

        tbl_selos.setBackground(new java.awt.Color(117, 214, 233));
        tbl_selos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbl_selos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. selo", "Selo utilizado", "Data", "Impresso?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_selos.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_selos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_selosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_selos);
        if (tbl_selos.getColumnModel().getColumnCount() > 0) {
            tbl_selos.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_selos.getColumnModel().getColumn(0).setMaxWidth(80);
            tbl_selos.getColumnModel().getColumn(1).setMinWidth(80);
            tbl_selos.getColumnModel().getColumn(1).setMaxWidth(100);
            tbl_selos.getColumnModel().getColumn(2).setMinWidth(80);
            tbl_selos.getColumnModel().getColumn(2).setMaxWidth(100);
            tbl_selos.getColumnModel().getColumn(3).setMinWidth(50);
            tbl_selos.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        tbl_pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. pessoa", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_pessoas);
        if (tbl_pessoas.getColumnModel().getColumnCount() > 0) {
            tbl_pessoas.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_pessoas.getColumnModel().getColumn(0).setMaxWidth(80);
            tbl_pessoas.getColumnModel().getColumn(1).setMinWidth(150);
            tbl_pessoas.getColumnModel().getColumn(1).setMaxWidth(200);
            tbl_pessoas.getColumnModel().getColumn(2).setMinWidth(150);
            tbl_pessoas.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        tbl_selos_selecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. selo", "Sequencia", "Custo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_selos_selecionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_selos_selecionadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_selos_selecionados);
        if (tbl_selos_selecionados.getColumnModel().getColumnCount() > 0) {
            tbl_selos_selecionados.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_selos_selecionados.getColumnModel().getColumn(0).setMaxWidth(80);
            tbl_selos_selecionados.getColumnModel().getColumn(1).setMinWidth(50);
            tbl_selos_selecionados.getColumnModel().getColumn(1).setMaxWidth(80);
            tbl_selos_selecionados.getColumnModel().getColumn(2).setMinWidth(30);
            tbl_selos_selecionados.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        btn_remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exchange.png"))); // NOI18N
        btn_remover.setText("Remover");
        btn_remover.setEnabled(false);
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_remover))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_remover)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/impressora.png"))); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.setFocusable(false);
        btn_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_imprimir);
        jToolBar1.add(jSeparator1);

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/stop_pequeno.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_sair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed

        // capturando os valores dos IDs dos selos que foram selecionados
        DefaultTableModel tabela = (DefaultTableModel) tbl_selos_selecionados.getModel();
        int total_linhas = tabela.getRowCount();

        // atributo que ira armazenar os selos escolhidos para impressão
        int selos_selecionados[] = {0, 0, 0, 0};

        if (total_linhas != 0) {

            // add valores no vetor sequencia[]
            for (int i = 0; i < total_linhas; i++) {
                int valor = Integer.parseInt(tabela.getValueAt(i, 0).toString());
                selos_selecionados[i] = valor;
            }

            // iremos alterar os valores dos combobox da tela de impressao de selos,
            // indicando assim as opções de relatorios
            String opt_localizacao[] = new String[2];

            opt_localizacao[0] = "Superior";
            opt_localizacao[1] = "Inferior";

            Imprimir_Relatorio rel = new Imprimir_Relatorio(null, false, opt_localizacao, Codigo_Atos_Model.CODIGO_RECONHECIMENTO, selos_selecionados);
            rel.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Atenção nenhum selo de reconhecimento foi selecionado", "Mensagem", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void tbl_selosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_selosMouseClicked

        if (evt.getClickCount() == 1) {
            int linha = tbl_selos.getSelectedRow();
            id_selo = tbl_selos.getValueAt(linha, 0).toString();
            preencher_tabela_pessoas(id_selo);

        } else if (evt.getClickCount() == 2) {
            int linha = tbl_selos.getSelectedRow();
            id_selo = tbl_selos.getValueAt(linha, 0).toString();
            preencher_lista_selecionada(id_selo);
        }

    }//GEN-LAST:event_tbl_selosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        grupoChecks.add(check_nao_impressos);
        grupoChecks.add(check_todos_reconhecimentos);
    }//GEN-LAST:event_formWindowOpened

    private void check_todos_reconhecimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_todos_reconhecimentosActionPerformed

        if (check_todos_reconhecimentos.isSelected()) {
            String sql = "select cadastro.tblselos.id, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.data_ato, cadastro.tblselos.impresso from cadastro.tblselos inner join cadastro.tblreconfirma on cadastro.tblreconfirma.id_selo = cadastro.tblselos.id";

            Reconhecer_Assinatura_Controller control = new Reconhecer_Assinatura_Controller();
            List<Selos_Model> info_selos = control.buscar_selos_utilizado_recon_firma(sql);
            preencher_tabela_selos(info_selos);
        }
    }//GEN-LAST:event_check_todos_reconhecimentosActionPerformed

    private void check_nao_impressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_nao_impressosActionPerformed
        if (check_nao_impressos.isSelected()) {
            String sql = "select cadastro.tblselos.id, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.data_ato, cadastro.tblselos.impresso from cadastro.tblselos inner join cadastro.tblreconfirma on cadastro.tblreconfirma.id_selo = cadastro.tblselos.id where cadastro.tblselos.impresso ='N' ";

            Reconhecer_Assinatura_Controller control = new Reconhecer_Assinatura_Controller();
            List<Selos_Model> info_selos = control.buscar_selos_utilizado_recon_firma(sql);
            preencher_tabela_selos(info_selos);
        }
    }//GEN-LAST:event_check_nao_impressosActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        String data_inicio = campo_data_inicial.getText();
        String data_fim = campo_data_fim.getText();

        DateTimeFormatter form = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate d1 = LocalDate.parse(data_inicio, form);
        LocalDate d2 = LocalDate.parse(data_fim, form);

        String sql_busca = "select cadastro.tblselos.data_ato, cadastro.tblselos.letras, cadastro.tblselos.selos, cadastro.tblselos.impresso, cadastro.tblselos.id from cadastro.tblselos inner join cadastro.tblreconfirma on cadastro.tblreconfirma.id_selo = cadastro.tblselos.id where cadastro.tblselos.data_ato >=' " + d1 + " ' " + " and cadastro.tblselos.data_ato <=' " + d2 + " ' ";

        Reconhecer_Assinatura_Controller control = new Reconhecer_Assinatura_Controller();
        List<Selos_Model> info_selos = control.buscar_selos_utilizado_recon_firma(sql_busca);

        preencher_tabela_selos(info_selos);

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void check_opt_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_opt_periodoActionPerformed

        if (check_opt_periodo.isSelected()) {
            campo_data_fim.setEnabled(true);
            campo_data_inicial.setEnabled(true);
            btn_buscar.setEnabled(true);
            campo_data_inicial.requestFocus();
        } else {
            campo_data_fim.setEnabled(false);
            campo_data_inicial.setEnabled(false);
            btn_buscar.setEnabled(false);
        }
    }//GEN-LAST:event_check_opt_periodoActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed

        DefaultTableModel tabela = (DefaultTableModel) tbl_selos_selecionados.getModel();
        linha_selecionada = tbl_selos_selecionados.getSelectedRow();

        if (tabela.getRowCount() != 0) {
            tabela.removeRow(linha_selecionada);
            contador--;
        } else {
            JOptionPane.showMessageDialog(this, "Ops... a tabela de selos para serem impressos não esta preenchida", "Mensagem", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void tbl_selos_selecionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_selos_selecionadosMouseClicked
        // atribuindo valor ao atributo linha_selecionada, assim ativamos o botao remover
        // para remover linhas da tabela de selos selecionados
        linha_selecionada = tbl_selos_selecionados.getSelectedRow();
        btn_remover.setEnabled(true);

    }//GEN-LAST:event_tbl_selos_selecionadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imprimir_Recon_Assinatura_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Imprimir_Recon_Assinatura_View dialog = new Imprimir_Recon_Assinatura_View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_remover;
    private javax.swing.JButton btn_sair;
    private javax.swing.JFormattedTextField campo_data_fim;
    private javax.swing.JFormattedTextField campo_data_inicial;
    private javax.swing.JCheckBox check_nao_impressos;
    private javax.swing.JCheckBox check_opt_periodo;
    private javax.swing.JCheckBox check_todos_reconhecimentos;
    private javax.swing.ButtonGroup grupoChecks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_pessoas;
    private javax.swing.JTable tbl_selos;
    private javax.swing.JTable tbl_selos_selecionados;
    // End of variables declaration//GEN-END:variables
}
