package View;

import Controller.Localizar_Controller;
import Model.Pessoas_Model;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jederson Andre
 */
public class Localizar_View extends javax.swing.JDialog {

    private int id_referencia;

    public int getId_outorgante() {
        return id_referencia;
    }

    /**
     * Creates new form Outorgantes
     */
    public Localizar_View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Metodo que ativa os botoes da tela Consulta conforme cada tela que chama
     *
     * @param alt - boolean ativa o botao Alterar - quando chamada da tela
     * Abertura de firma
     * @param recFir - boolean ativa o botao reconhecer assin. - quando cham.
     * tela reconhecer Ass.
     * @param lancProc - boolean ativa o botao lançar em procuração - quando
     * cham tela procuracao
     * @return
     */
    public int ativarBotoesConsultar(boolean alt, boolean recFir, boolean lancProc) {

        if (alt == true) {
            btnAlterarDados.setEnabled(true);
        } else if (recFir == true) {
            btnReconhecerAssinat.setEnabled(true);
        } else if (lancProc == true) {
            btnProcuracao.setEnabled(true);
        }

        // exibir tela
        this.setVisible(true);

        return id_referencia;
    }

    public void read(List<Pessoas_Model> dados) {
        /**
         * Para mostrar os dados na tabela que criamos, precisamos alterar o
         * model(), recuperando o model, dentro desse metodo temos um atributo
         * String nomeP, que recebe valores que ira ser pesquisado no BD.
         */
        DefaultTableModel modelo = (DefaultTableModel) jtConsulta.getModel();
        modelo.setNumRows(0); // Utilizado para nao repetir as linhas ao clicarmos duas vezes em pesquisar.

        for (Pessoas_Model l : dados) {

            // inserindo valores nas linhas
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNome(),
                l.getDocIdentidade(),
                l.getCpf(),
                l.getFicha()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();
        btnProcuracao = new javax.swing.JButton();
        btnReconhecerAssinat = new javax.swing.JButton();
        btnAlterarDados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelPesquisaNome = new javax.swing.JLabel();
        campoPsqNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione um cliente");

        jPanel2.setBackground(new java.awt.Color(150, 166, 166));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(178, 190, 185));

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RG", "CPF", "Ficha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtConsultaMouseClicked(evt);
            }
        });
        jtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtConsultaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtConsulta);
        if (jtConsulta.getColumnModel().getColumnCount() > 0) {
            jtConsulta.getColumnModel().getColumn(0).setMinWidth(20);
            jtConsulta.getColumnModel().getColumn(0).setMaxWidth(50);
            jtConsulta.getColumnModel().getColumn(4).setMinWidth(30);
            jtConsulta.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        btnProcuracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/files.png"))); // NOI18N
        btnProcuracao.setText("Lançar em procuração");
        btnProcuracao.setEnabled(false);
        btnProcuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcuracaoActionPerformed(evt);
            }
        });

        btnReconhecerAssinat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/notepad.png"))); // NOI18N
        btnReconhecerAssinat.setText("Reconhecer Assinatura");
        btnReconhecerAssinat.setEnabled(false);
        btnReconhecerAssinat.setPreferredSize(new java.awt.Dimension(121, 44));
        btnReconhecerAssinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconhecerAssinatActionPerformed(evt);
            }
        });

        btnAlterarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        btnAlterarDados.setText("Alterar");
        btnAlterarDados.setEnabled(false);
        btnAlterarDados.setPreferredSize(new java.awt.Dimension(121, 44));
        btnAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarDadosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Consulta_SAIR.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelPesquisaNome.setText("Localizar por NOME:");

        campoPsqNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPsqNomeKeyPressed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPesquisaNome)
                .addGap(18, 18, 18)
                .addComponent(campoPsqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPesquisaNome)
                    .addComponent(campoPsqNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReconhecerAssinat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReconhecerAssinat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtConsultaMouseClicked

        // COMANDO QUE CAPTURA A LINHA QUE FOI SELECIONADA ATRAVES DO METODO GETSELECTROW()
        //PASSANDO PARA O ATRIBUTO LINHA. LOGO RECUPERAMOS O MODEL DA TABELA E CAPTURA
        //A INFORMAÇÃO QUE ESTA NA LINHA E COLUNA INDICADA NO METODO GETVALUEAT(LINHA,COLUNA)
        //PASSANDO PARA A CLASSE CADPESSOA;
        int linha = jtConsulta.getSelectedRow(); // capiturando a linha selecionada

        id_referencia = Integer.parseInt(jtConsulta.getModel().getValueAt(linha, 0).toString());

    }//GEN-LAST:event_jtConsultaMouseClicked

    private void jtConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtConsultaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtConsultaKeyPressed

    private void btnProcuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcuracaoActionPerformed
        // verificando id_outorgante foi selecionado
        if (id_referencia != 0) {
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma Pessoa", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnProcuracaoActionPerformed

    private void btnReconhecerAssinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconhecerAssinatActionPerformed
        // verificando id_outorgante foi selecionado
        if (id_referencia != 0) {
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma Pessoa", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnReconhecerAssinatActionPerformed

    private void btnAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarDadosActionPerformed
        // verificando id_outorgante foi selecionado
        if (id_referencia == 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma Pessoa", "Campo não selecionado", JOptionPane.ERROR_MESSAGE);
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnAlterarDadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // SAINDO
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String like = campoPsqNome.getText();

        Localizar_Controller pesq = new Localizar_Controller();
        List<Pessoas_Model> pesquisarNome = pesq.pesquisarNome(like);

        read(pesquisarNome);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void campoPsqNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPsqNomeKeyPressed
        // ENTER        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPesquisar.requestFocus();
        }

    }//GEN-LAST:event_campoPsqNomeKeyPressed

    private void btnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            String like = campoPsqNome.getText();
            
            Localizar_Controller pesq = new Localizar_Controller();
            List<Pessoas_Model> pesquisarNome = pesq.pesquisarNome(like);

            read(pesquisarNome);
        }

    }//GEN-LAST:event_btnPesquisarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Localizar_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Localizar_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Localizar_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Localizar_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Localizar_View dialog = new Localizar_View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAlterarDados;
    private javax.swing.JButton btnPesquisar;
    public static javax.swing.JButton btnProcuracao;
    public static javax.swing.JButton btnReconhecerAssinat;
    private javax.swing.JTextField campoPsqNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtConsulta;
    private javax.swing.JLabel labelPesquisaNome;
    // End of variables declaration//GEN-END:variables
}
