/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Enderecos_Controller;
import Model.Enderecos_Model;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class Localizar_Enderecos_View extends javax.swing.JDialog {

    int id_endereco;

    /**
     * Creates new form Localizar_Enderecos_View
     */
    public Localizar_Enderecos_View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Metodo que preenche a tabela com as informações dos enderecos cadastrados
     * na base de dados
     *
     * @param lista_end
     */
    private void Preencher_Tabela_Endereco(List<Enderecos_Model> lista_end) {

        DefaultTableModel tabela = (DefaultTableModel) tbl_enderecos.getModel();
        tabela.setNumRows(0);

        for (Enderecos_Model enderecos : lista_end) {
            tabela.addRow(new Object[]{
                enderecos.getId_endereco(),
                enderecos.getNome_rua(),
                enderecos.getBairro()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        btnBuscarEnderecos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_enderecos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Endereço");
        setResizable(false);

        jLabel1.setText("Buscar por:");

        btnBuscarEnderecos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Consulta_LOCALIZAR.png"))); // NOI18N
        btnBuscarEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEnderecosActionPerformed(evt);
            }
        });

        tbl_enderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Bairro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_enderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_enderecosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_enderecos);
        if (tbl_enderecos.getColumnModel().getColumnCount() > 0) {
            tbl_enderecos.getColumnModel().getColumn(0).setMinWidth(15);
            tbl_enderecos.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_enderecos.getColumnModel().getColumn(2).setMinWidth(50);
            tbl_enderecos.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button_ok_pequeno.png"))); // NOI18N
        jButton1.setToolTipText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarEnderecos)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarEnderecos)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEnderecosActionPerformed
        // capturando conteudo fornecido
        String localizar = campoDescricao.getText();
        // instanciando objeto DAO
        Enderecos_Controller buscar_end = new Enderecos_Controller();

        // chamando metodo responsavel
        // e capturando o retorno com a lista dos objetos
        List<Enderecos_Model> lista_enderecos = buscar_end.Buscar_Endereco(localizar);

        // chamando metodo que ira preencher a tabela
        Preencher_Tabela_Endereco(lista_enderecos);
    }//GEN-LAST:event_btnBuscarEnderecosActionPerformed

    private void tbl_enderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_enderecosMouseClicked
        // capturando o ID escolhido
        int linha = tbl_enderecos.getSelectedRow();
        this.id_endereco = Integer.parseInt(tbl_enderecos.getValueAt(linha, 0).toString());
        
//        System.out.println(id_endereco);
    }//GEN-LAST:event_tbl_enderecosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Localizar_Enderecos_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Localizar_Enderecos_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Localizar_Enderecos_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Localizar_Enderecos_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Localizar_Enderecos_View dialog = new Localizar_Enderecos_View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEnderecos;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_enderecos;
    // End of variables declaration//GEN-END:variables
}
