package View;

import View.CadUsuario_View;
import com.cartorio.selos.FormNovaSeqSelos;
import com.cartorio.suporte.Contato;
import java.io.IOException;
import java.text.DateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author Jederson Andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * Metodo construtor que recebe os valores que irão habilitar determinados
     * botoes e itens de menus, conforme tblpermissao do banco de dados
     *
     * @param aut
     * @param recF
     * @param abF
     * @param proc
     * @param casm
     * @param nasc
     * @param obt
     * @param altSelo
     * @param nvUser
     */
    public Principal(boolean aut, boolean recF, boolean abF, boolean proc, boolean casm, boolean nasc, boolean obt, boolean altSelo, boolean nvUser) {
        initComponents();
        btnAutenticacao.setEnabled(aut);
        btnReconhecimento.setEnabled(recF);
        btnNovaFicha.setEnabled(abF);
        btnAlteraSelos.setEnabled(altSelo);

        // itens de menu
        menuAutenticacao.setEnabled(aut);
        menuProcuracao.setEnabled(proc);
        menuCasamento.setEnabled(casm);
        menuNascimento.setEnabled(nasc);
        menuObito.setEnabled(obt);
        menuAlterarSelo.setEnabled(altSelo);
        menuNovoUsuario.setEnabled(nvUser);
        menuNovaFicha.setEnabled(abF);
        menuReconAssinatura.setEnabled(recF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanelRodape = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovaFicha = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnAutenticacao = new javax.swing.JButton();
        btnReconhecimento = new javax.swing.JButton();
        btnAlteraSelos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHoras = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCad = new javax.swing.JMenu();
        menuNovaFicha = new javax.swing.JMenuItem();
        menuAlterarSelo = new javax.swing.JMenuItem();
        menuNovoUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuProcuracao = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuAutenticacao = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuReconAssinatura = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuNascimento = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuCasamento = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuObito = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        calculadora = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        MenuItemSair = new javax.swing.JMenuItem();

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SICC - Sistema de Controle para Cartorios");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblData.setText("Data");

        javax.swing.GroupLayout jPanelRodapeLayout = new javax.swing.GroupLayout(jPanelRodape);
        jPanelRodape.setLayout(jPanelRodapeLayout);
        jPanelRodapeLayout.setHorizontalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRodapeLayout.setVerticalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNovaFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/nova ficha.png"))); // NOI18N
        btnNovaFicha.setText("Nova Firma");
        btnNovaFicha.setToolTipText("Nova ficha assinatura");
        btnNovaFicha.setBorderPainted(false);
        btnNovaFicha.setEnabled(false);
        btnNovaFicha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovaFicha.setPreferredSize(new java.awt.Dimension(100, 100));
        btnNovaFicha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaFichaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovaFicha);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Principal_localizar.png"))); // NOI18N
        btnConsultar.setText("Localizar Firma");
        btnConsultar.setToolTipText("Localizar pessoa");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setPreferredSize(new java.awt.Dimension(120, 100));
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultar);

        btnAutenticacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Principal_Autenticação.png"))); // NOI18N
        btnAutenticacao.setText("Autenticação");
        btnAutenticacao.setToolTipText("Autenticação");
        btnAutenticacao.setBorderPainted(false);
        btnAutenticacao.setEnabled(false);
        btnAutenticacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAutenticacao.setPreferredSize(new java.awt.Dimension(120, 100));
        btnAutenticacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutenticacaoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAutenticacao);

        btnReconhecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reconhecimento ASSINATURA.png"))); // NOI18N
        btnReconhecimento.setText("Reconhecimento");
        btnReconhecimento.setToolTipText("Reconhecimento de firma");
        btnReconhecimento.setBorderPainted(false);
        btnReconhecimento.setEnabled(false);
        btnReconhecimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReconhecimento.setPreferredSize(new java.awt.Dimension(130, 100));
        btnReconhecimento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReconhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconhecimentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReconhecimento);

        btnAlteraSelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/diagram_v2_26.png"))); // NOI18N
        btnAlteraSelos.setText("Alterar selos");
        btnAlteraSelos.setToolTipText("Opções de selos");
        btnAlteraSelos.setBorderPainted(false);
        btnAlteraSelos.setEnabled(false);
        btnAlteraSelos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlteraSelos.setMaximumSize(new java.awt.Dimension(85, 97));
        btnAlteraSelos.setMinimumSize(new java.awt.Dimension(85, 97));
        btnAlteraSelos.setPreferredSize(new java.awt.Dimension(130, 100));
        btnAlteraSelos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlteraSelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraSelosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlteraSelos);

        lblHoras.setFont(new java.awt.Font("DS-Digital", 1, 36)); // NOI18N

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/stop_grnde.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setPreferredSize(new java.awt.Dimension(130, 100));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(lblHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jMenuBar1.setFont(new java.awt.Font("TlwgTypewriter", 0, 14)); // NOI18N

        MenuCad.setText("Cadastro");
        MenuCad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        menuNovaFicha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuNovaFicha.setText("Nova ficha");
        menuNovaFicha.setEnabled(false);
        menuNovaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaFichaActionPerformed(evt);
            }
        });
        MenuCad.add(menuNovaFicha);

        menuAlterarSelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuAlterarSelo.setText("Alterar selos");
        menuAlterarSelo.setEnabled(false);
        menuAlterarSelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarSeloActionPerformed(evt);
            }
        });
        MenuCad.add(menuAlterarSelo);

        menuNovoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuNovoUsuario.setText("Novo Usuario");
        menuNovoUsuario.setEnabled(false);
        menuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoUsuarioActionPerformed(evt);
            }
        });
        MenuCad.add(menuNovoUsuario);

        jMenuBar1.add(MenuCad);

        jMenu2.setText("Atos");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        menuProcuracao.setText("Procuração");
        menuProcuracao.setEnabled(false);

        jMenuItem10.setText("Nova Procuração");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuProcuracao.add(jMenuItem10);

        jMenu2.add(menuProcuracao);

        jMenu5.setText("Autenticações");

        menuAutenticacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAutenticacao.setText("Autenticação");
        menuAutenticacao.setEnabled(false);
        menuAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAutenticacaoActionPerformed(evt);
            }
        });
        jMenu5.add(menuAutenticacao);

        jMenuItem4.setText("Imprimir selo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenu2.add(jMenu5);

        jMenu7.setText("Reconhecimento");

        menuReconAssinatura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuReconAssinatura.setText("Reconhecer");
        menuReconAssinatura.setEnabled(false);
        menuReconAssinatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReconAssinaturaActionPerformed(evt);
            }
        });
        jMenu7.add(menuReconAssinatura);

        jMenuItem7.setText("Imprimir selo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Certidões");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenu3.add(jSeparator1);

        menuNascimento.setText("Registro de Nascimento");
        menuNascimento.setEnabled(false);

        jMenuItem1.setText("Nova Certidao");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuNascimento.add(jMenuItem1);

        jMenuItem2.setText("Pesquisar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuNascimento.add(jMenuItem2);

        jMenuItem5.setText("Alterar registrando");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuNascimento.add(jMenuItem5);

        jMenu3.add(menuNascimento);

        jMenu1.setText("Registro de Casamento");

        menuCasamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuCasamento.setText("Novo Proc. Casamento");
        menuCasamento.setEnabled(false);
        menuCasamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCasamentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCasamento);

        jMenuItem3.setText("Pesquisar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu3.add(jMenu1);

        jMenu4.setText("Registro de Obito");

        menuObito.setText("Novo Obito");
        menuObito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObitoActionPerformed(evt);
            }
        });
        jMenu4.add(menuObito);

        jMenuItem9.setText("Alterar obito");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Relatorios");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem8.setText("Lancamentos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuBar1.add(jMenu8);

        jMenu6.setBackground(new java.awt.Color(201, 123, 45));
        jMenu6.setText("Suporte");
        jMenu6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem6.setBackground(new java.awt.Color(197, 191, 184));
        jMenuItem6.setText("Contato");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        calculadora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        calculadora.setText("Calculadora");
        calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraActionPerformed(evt);
            }
        });
        jMenu6.add(calculadora);

        jMenuBar1.add(jMenu6);

        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });

        MenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuItemSair.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        MenuItemSair.setText("SAIR");
        MenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairActionPerformed(evt);
            }
        });
        MenuSair.add(MenuItemSair);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                .addComponent(jPanelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1022, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que mostra as horas no label tela principal
     */
    private void mostrarHoras() {

        Timer time = new Timer();
        TimerTask task;
        final DateTimeFormatter formt = DateTimeFormatter.ofPattern("hh:mm:ss");

        long segundos = 1000;

        task = new TimerTask() {
            @Override
            public void run() {

                LocalTime timeAgora = LocalTime.now();
                lblHoras.setText(String.valueOf(formt.format(timeAgora)));
            }
        };
        time.scheduleAtFixedRate(task, 0, segundos);
    }
    private void btnNovaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaFichaActionPerformed

        Abertura_Assinatura_View cadastrar = new Abertura_Assinatura_View();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_btnNovaFichaActionPerformed

    private void menuReconAssinaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReconAssinaturaActionPerformed
        // TODO add your handling code here:
        Reconhecer_Assinatura_View recFirma = new Reconhecer_Assinatura_View();
        recFirma.setVisible(true);
    }//GEN-LAST:event_menuReconAssinaturaActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
/*
        TelaProcuracao proc = new TelaProcuracao();
        proc.setVisible(true);
*/
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Localizar_View_2 tela = new Localizar_View_2(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutenticacaoActionPerformed
        // TODO add your handling code here:
        Autenticacao_View autenticar = new Autenticacao_View();
        autenticar.setVisible(true);
    }//GEN-LAST:event_btnAutenticacaoActionPerformed

    private void btnAlteraSelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraSelosActionPerformed
        // TODO add your handling code here:
        Cadastro_Selos novo = new Cadastro_Selos(this, true);
        novo.setVisible(true);
    }//GEN-LAST:event_btnAlteraSelosActionPerformed

    private void menuNovaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaFichaActionPerformed
        // TODO add your handling code here:
        Abertura_Assinatura_View abrir = new Abertura_Assinatura_View();
        abrir.setVisible(true);

    }//GEN-LAST:event_menuNovaFichaActionPerformed

    private void menuAlterarSeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarSeloActionPerformed
        // TODO add your handling code here:
        FormNovaSeqSelos abrir = new FormNovaSeqSelos();
        abrir.setVisible(true);

    }//GEN-LAST:event_menuAlterarSeloActionPerformed

    private void menuAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAutenticacaoActionPerformed
        // TODO add your handling code here:

        Autenticacao_View abrir = new Autenticacao_View();
        abrir.setVisible(true);
    }//GEN-LAST:event_menuAutenticacaoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
        lblData.setText(formatador.format(data));

        mostrarHoras();

    }//GEN-LAST:event_formWindowActivated

    private void menuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoUsuarioActionPerformed
        // TODO add your handling code here:
        CadUsuario_View novoUser = new CadUsuario_View();
        novoUser.setVisible(true);

    }//GEN-LAST:event_menuNovoUsuarioActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuSairActionPerformed

    private void btnReconhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconhecimentoActionPerformed
        // TODO add your handling code here:
        Reconhecer_Assinatura_View tela = new Reconhecer_Assinatura_View();
        tela.setVisible(true);
    }//GEN-LAST:event_btnReconhecimentoActionPerformed

    private void MenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuItemSairActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Contato cont = new Contato();
        cont.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraActionPerformed
        try {
            Process calc = Runtime.getRuntime().exec("calc.exe");

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro na abertura de processo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calculadoraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Certidao de Nascimento
        Certidao_Nascimento cert = new Certidao_Nascimento(this, false);
        cert.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // tela de pesquisar certidao
        Localizar_Cert_Nascimento_View buscar = new Localizar_Cert_Nascimento_View();
        buscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuCasamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCasamentoActionPerformed
        // TODO add your handling code here:
        Casamento_View casam = new Casamento_View();
        casam.setVisible(true);
    }//GEN-LAST:event_menuCasamentoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // tela de pesquisar certidao
        Localizar_Cert_Nascimento_View buscar = new Localizar_Cert_Nascimento_View();
        buscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuObitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObitoActionPerformed
        
        Obito_View obito = new Obito_View();
        obito.setVisible(true);
    }//GEN-LAST:event_menuObitoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Tela utilizada para imprimir selos de autenticações
        Impressao_Autenticacao_View autenticacao = new Impressao_Autenticacao_View(this, false);
        autenticacao.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // tela para alterar dados do registrando 
        Alterar_Registrando_View alterar = new Alterar_Registrando_View(this, true);
        alterar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Imprimir_Recon_Assinatura_View view = new Imprimir_Recon_Assinatura_View(this, false);
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Lancamentos_View lancamento = new Lancamentos_View(this, false);
        lancamento.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Alterar_Obito_View localizar = new Alterar_Obito_View(this, false);
        localizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    public static void main(String args[]) {
        Principal tela = new Principal();
        tela.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu MenuCad;
    private javax.swing.JMenuItem MenuItemSair;
    private javax.swing.JMenu MenuSair;
    public static javax.swing.JButton btnAlteraSelos;
    private javax.swing.JButton btnAutenticacao;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnNovaFicha;
    private javax.swing.JButton btnReconhecimento;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem calculadora;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRodape;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHoras;
    public static javax.swing.JMenuItem menuAlterarSelo;
    private javax.swing.JMenuItem menuAutenticacao;
    private javax.swing.JMenuItem menuCasamento;
    private javax.swing.JMenu menuNascimento;
    private javax.swing.JMenuItem menuNovaFicha;
    public static javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenuItem menuObito;
    private javax.swing.JMenu menuProcuracao;
    private javax.swing.JMenuItem menuReconAssinatura;
    // End of variables declaration//GEN-END:variables
}
